package com.kunfei.bookshelf.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kunfei.bookshelf.bean.BookmarksBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "BOOKMARKS_BEAN".
 */
public class BookmarksBeanDao extends AbstractDao<BookmarksBean, Long> {

    public static final String TABLENAME = "BOOKMARKS_BEAN";

    public BookmarksBeanDao(DaoConfig config) {
        super(config);
    }


    public BookmarksBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOKMARKS_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"ICON_URL\" TEXT," + // 2: icon_url
                "\"URL\" TEXT," + // 3: url
                "\"CREATE_TIME\" TEXT);"); // 4: create_time
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOKMARKS_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookmarksBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }

        String icon_url = entity.getIcon_url();
        if (icon_url != null) {
            stmt.bindString(3, icon_url);
        }

        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(4, url);
        }

        String create_time = entity.getCreate_time();
        if (create_time != null) {
            stmt.bindString(5, create_time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookmarksBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }

        String icon_url = entity.getIcon_url();
        if (icon_url != null) {
            stmt.bindString(3, icon_url);
        }

        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(4, url);
        }

        String create_time = entity.getCreate_time();
        if (create_time != null) {
            stmt.bindString(5, create_time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }

    @Override
    public BookmarksBean readEntity(Cursor cursor, int offset) {
        BookmarksBean entity = new BookmarksBean( //
                cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // icon_url
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // url
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // create_time
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, BookmarksBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIcon_url(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCreate_time(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
    }

    @Override
    protected final Long updateKeyAfterInsert(BookmarksBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(BookmarksBean entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookmarksBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity BookmarksBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Icon_url = new Property(2, String.class, "icon_url", false, "ICON_URL");
        public final static Property Url = new Property(3, String.class, "url", false, "URL");
        public final static Property Create_time = new Property(4, String.class, "create_time", false, "CREATE_TIME");
    }

}
