package com.kunfei.bookshelf.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.kunfei.bookshelf.bean.AdBlockingUserBean;
import com.kunfei.bookshelf.bean.BookInfoBean;
import com.kunfei.bookshelf.bean.BookmarkBean;
import com.kunfei.bookshelf.bean.BookmarksBean;
import com.kunfei.bookshelf.bean.BookShelfBean;
import com.kunfei.bookshelf.bean.BookSourceBean;
import com.kunfei.bookshelf.bean.ChapterListBean;
import com.kunfei.bookshelf.bean.CollectionBean;
import com.kunfei.bookshelf.bean.CookieBean;
import com.kunfei.bookshelf.bean.ReplaceRuleBean;
import com.kunfei.bookshelf.bean.SearchBookBean;
import com.kunfei.bookshelf.bean.SearchHistoryBean;
import com.kunfei.bookshelf.bean.SearchplBean;
import com.kunfei.bookshelf.bean.TabMagBean;
import com.kunfei.bookshelf.bean.WebHistoryBean;

import com.kunfei.bookshelf.dao.AdBlockingUserBeanDao;
import com.kunfei.bookshelf.dao.BookInfoBeanDao;
import com.kunfei.bookshelf.dao.BookmarkBeanDao;
import com.kunfei.bookshelf.dao.BookmarksBeanDao;
import com.kunfei.bookshelf.dao.BookShelfBeanDao;
import com.kunfei.bookshelf.dao.BookSourceBeanDao;
import com.kunfei.bookshelf.dao.ChapterListBeanDao;
import com.kunfei.bookshelf.dao.CollectionBeanDao;
import com.kunfei.bookshelf.dao.CookieBeanDao;
import com.kunfei.bookshelf.dao.ReplaceRuleBeanDao;
import com.kunfei.bookshelf.dao.SearchBookBeanDao;
import com.kunfei.bookshelf.dao.SearchHistoryBeanDao;
import com.kunfei.bookshelf.dao.SearchplBeanDao;
import com.kunfei.bookshelf.dao.TabMagBeanDao;
import com.kunfei.bookshelf.dao.WebHistoryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adBlockingUserBeanDaoConfig;
    private final DaoConfig bookInfoBeanDaoConfig;
    private final DaoConfig bookmarkBeanDaoConfig;
    private final DaoConfig bookmarksBeanDaoConfig;
    private final DaoConfig bookShelfBeanDaoConfig;
    private final DaoConfig bookSourceBeanDaoConfig;
    private final DaoConfig chapterListBeanDaoConfig;
    private final DaoConfig collectionBeanDaoConfig;
    private final DaoConfig cookieBeanDaoConfig;
    private final DaoConfig replaceRuleBeanDaoConfig;
    private final DaoConfig searchBookBeanDaoConfig;
    private final DaoConfig searchHistoryBeanDaoConfig;
    private final DaoConfig searchplBeanDaoConfig;
    private final DaoConfig tabMagBeanDaoConfig;
    private final DaoConfig webHistoryBeanDaoConfig;

    private final AdBlockingUserBeanDao adBlockingUserBeanDao;
    private final BookInfoBeanDao bookInfoBeanDao;
    private final BookmarkBeanDao bookmarkBeanDao;
    private final BookmarksBeanDao bookmarksBeanDao;
    private final BookShelfBeanDao bookShelfBeanDao;
    private final BookSourceBeanDao bookSourceBeanDao;
    private final ChapterListBeanDao chapterListBeanDao;
    private final CollectionBeanDao collectionBeanDao;
    private final CookieBeanDao cookieBeanDao;
    private final ReplaceRuleBeanDao replaceRuleBeanDao;
    private final SearchBookBeanDao searchBookBeanDao;
    private final SearchHistoryBeanDao searchHistoryBeanDao;
    private final SearchplBeanDao searchplBeanDao;
    private final TabMagBeanDao tabMagBeanDao;
    private final WebHistoryBeanDao webHistoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adBlockingUserBeanDaoConfig = daoConfigMap.get(AdBlockingUserBeanDao.class).clone();
        adBlockingUserBeanDaoConfig.initIdentityScope(type);

        bookInfoBeanDaoConfig = daoConfigMap.get(BookInfoBeanDao.class).clone();
        bookInfoBeanDaoConfig.initIdentityScope(type);

        bookmarkBeanDaoConfig = daoConfigMap.get(BookmarkBeanDao.class).clone();
        bookmarkBeanDaoConfig.initIdentityScope(type);

        bookmarksBeanDaoConfig = daoConfigMap.get(BookmarksBeanDao.class).clone();
        bookmarksBeanDaoConfig.initIdentityScope(type);

        bookShelfBeanDaoConfig = daoConfigMap.get(BookShelfBeanDao.class).clone();
        bookShelfBeanDaoConfig.initIdentityScope(type);

        bookSourceBeanDaoConfig = daoConfigMap.get(BookSourceBeanDao.class).clone();
        bookSourceBeanDaoConfig.initIdentityScope(type);

        chapterListBeanDaoConfig = daoConfigMap.get(ChapterListBeanDao.class).clone();
        chapterListBeanDaoConfig.initIdentityScope(type);

        collectionBeanDaoConfig = daoConfigMap.get(CollectionBeanDao.class).clone();
        collectionBeanDaoConfig.initIdentityScope(type);

        cookieBeanDaoConfig = daoConfigMap.get(CookieBeanDao.class).clone();
        cookieBeanDaoConfig.initIdentityScope(type);

        replaceRuleBeanDaoConfig = daoConfigMap.get(ReplaceRuleBeanDao.class).clone();
        replaceRuleBeanDaoConfig.initIdentityScope(type);

        searchBookBeanDaoConfig = daoConfigMap.get(SearchBookBeanDao.class).clone();
        searchBookBeanDaoConfig.initIdentityScope(type);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        searchplBeanDaoConfig = daoConfigMap.get(SearchplBeanDao.class).clone();
        searchplBeanDaoConfig.initIdentityScope(type);

        tabMagBeanDaoConfig = daoConfigMap.get(TabMagBeanDao.class).clone();
        tabMagBeanDaoConfig.initIdentityScope(type);

        webHistoryBeanDaoConfig = daoConfigMap.get(WebHistoryBeanDao.class).clone();
        webHistoryBeanDaoConfig.initIdentityScope(type);

        adBlockingUserBeanDao = new AdBlockingUserBeanDao(adBlockingUserBeanDaoConfig, this);
        bookInfoBeanDao = new BookInfoBeanDao(bookInfoBeanDaoConfig, this);
        bookmarkBeanDao = new BookmarkBeanDao(bookmarkBeanDaoConfig, this);
        bookmarksBeanDao = new BookmarksBeanDao(bookmarksBeanDaoConfig, this);
        bookShelfBeanDao = new BookShelfBeanDao(bookShelfBeanDaoConfig, this);
        bookSourceBeanDao = new BookSourceBeanDao(bookSourceBeanDaoConfig, this);
        chapterListBeanDao = new ChapterListBeanDao(chapterListBeanDaoConfig, this);
        collectionBeanDao = new CollectionBeanDao(collectionBeanDaoConfig, this);
        cookieBeanDao = new CookieBeanDao(cookieBeanDaoConfig, this);
        replaceRuleBeanDao = new ReplaceRuleBeanDao(replaceRuleBeanDaoConfig, this);
        searchBookBeanDao = new SearchBookBeanDao(searchBookBeanDaoConfig, this);
        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);
        searchplBeanDao = new SearchplBeanDao(searchplBeanDaoConfig, this);
        tabMagBeanDao = new TabMagBeanDao(tabMagBeanDaoConfig, this);
        webHistoryBeanDao = new WebHistoryBeanDao(webHistoryBeanDaoConfig, this);

        registerDao(AdBlockingUserBean.class, adBlockingUserBeanDao);
        registerDao(BookInfoBean.class, bookInfoBeanDao);
        registerDao(BookmarkBean.class, bookmarkBeanDao);
        registerDao(BookmarksBean.class, bookmarksBeanDao);
        registerDao(BookShelfBean.class, bookShelfBeanDao);
        registerDao(BookSourceBean.class, bookSourceBeanDao);
        registerDao(ChapterListBean.class, chapterListBeanDao);
        registerDao(CollectionBean.class, collectionBeanDao);
        registerDao(CookieBean.class, cookieBeanDao);
        registerDao(ReplaceRuleBean.class, replaceRuleBeanDao);
        registerDao(SearchBookBean.class, searchBookBeanDao);
        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
        registerDao(SearchplBean.class, searchplBeanDao);
        registerDao(TabMagBean.class, tabMagBeanDao);
        registerDao(WebHistoryBean.class, webHistoryBeanDao);
    }

    public void clear() {
        adBlockingUserBeanDaoConfig.clearIdentityScope();
        bookInfoBeanDaoConfig.clearIdentityScope();
        bookmarkBeanDaoConfig.clearIdentityScope();
        bookmarksBeanDaoConfig.clearIdentityScope();
        bookShelfBeanDaoConfig.clearIdentityScope();
        bookSourceBeanDaoConfig.clearIdentityScope();
        chapterListBeanDaoConfig.clearIdentityScope();
        collectionBeanDaoConfig.clearIdentityScope();
        cookieBeanDaoConfig.clearIdentityScope();
        replaceRuleBeanDaoConfig.clearIdentityScope();
        searchBookBeanDaoConfig.clearIdentityScope();
        searchHistoryBeanDaoConfig.clearIdentityScope();
        searchplBeanDaoConfig.clearIdentityScope();
        tabMagBeanDaoConfig.clearIdentityScope();
        webHistoryBeanDaoConfig.clearIdentityScope();
    }

    public AdBlockingUserBeanDao getAdBlockingUserBeanDao() {
        return adBlockingUserBeanDao;
    }

    public BookInfoBeanDao getBookInfoBeanDao() {
        return bookInfoBeanDao;
    }

    public BookmarkBeanDao getBookmarkBeanDao() {
        return bookmarkBeanDao;
    }

    public BookmarksBeanDao getBookmarksBeanDao() {
        return bookmarksBeanDao;
    }

    public BookShelfBeanDao getBookShelfBeanDao() {
        return bookShelfBeanDao;
    }

    public BookSourceBeanDao getBookSourceBeanDao() {
        return bookSourceBeanDao;
    }

    public ChapterListBeanDao getChapterListBeanDao() {
        return chapterListBeanDao;
    }

    public CollectionBeanDao getCollectionBeanDao() {
        return collectionBeanDao;
    }

    public CookieBeanDao getCookieBeanDao() {
        return cookieBeanDao;
    }

    public ReplaceRuleBeanDao getReplaceRuleBeanDao() {
        return replaceRuleBeanDao;
    }

    public SearchBookBeanDao getSearchBookBeanDao() {
        return searchBookBeanDao;
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

    public SearchplBeanDao getSearchplBeanDao() {
        return searchplBeanDao;
    }

    public TabMagBeanDao getTabMagBeanDao() {
        return tabMagBeanDao;
    }

    public WebHistoryBeanDao getWebHistoryBeanDao() {
        return webHistoryBeanDao;
    }

}
