package com.kunfei.bookshelf.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.kunfei.bookshelf.bean.WebHistoryBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "WEB_HISTORY_BEAN".
 */
public class WebHistoryBeanDao extends AbstractDao<WebHistoryBean, Long> {

    public static final String TABLENAME = "WEB_HISTORY_BEAN";

    public WebHistoryBeanDao(DaoConfig config) {
        super(config);
    }


    public WebHistoryBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEB_HISTORY_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"TIME\" TEXT," + // 1: time
                "\"TITLE\" TEXT," + // 2: title
                "\"WEB_URL\" TEXT," + // 3: webUrl
                "\"ICON\" TEXT);"); // 4: icon
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEB_HISTORY_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WebHistoryBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());

        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(2, time);
        }

        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }

        String webUrl = entity.getWebUrl();
        if (webUrl != null) {
            stmt.bindString(4, webUrl);
        }

        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(5, icon);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WebHistoryBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());

        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(2, time);
        }

        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }

        String webUrl = entity.getWebUrl();
        if (webUrl != null) {
            stmt.bindString(4, webUrl);
        }

        String icon = entity.getIcon();
        if (icon != null) {
            stmt.bindString(5, icon);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }

    @Override
    public WebHistoryBean readEntity(Cursor cursor, int offset) {
        WebHistoryBean entity = new WebHistoryBean( //
                cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // time
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // webUrl
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // icon
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, WebHistoryBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWebUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIcon(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
    }

    @Override
    protected final Long updateKeyAfterInsert(WebHistoryBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(WebHistoryBean entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WebHistoryBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity WebHistoryBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Time = new Property(1, String.class, "time", false, "TIME");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property WebUrl = new Property(3, String.class, "webUrl", false, "WEB_URL");
        public final static Property Icon = new Property(4, String.class, "icon", false, "ICON");
    }

}
